// Generated by CoffeeScript 1.6.1
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.get('/phones/phones.json', function(req, res, next) {
    var jsonObj;
    console.log('Get request called for the url /phones/phones.json');
    res.header({
      'Content-Type': 'application/json'
    });
    jsonObj = [];
    jsonObj.push({
      name: 'claudia',
      url: 'claudia url'
    });
    jsonObj.push({
      name: 'rita',
      url: 'rita url'
    });
    return res.end(JSON.stringify(jsonObj));
  });

  app.configure(function() {
    return app.use("/", express["static"]('public'));
  });

  app.listen(3000);

  console.log("Web Server running at http://127.0.0.1:3000/");

}).call(this);
